Sidebar top CPU time & allocated memory (by percent)
glowroot/glowroot pull request #724
Opened 2020-06-03 19:18 UTC by ionutursuleanu

Hi @trask 

I added the option to sort by total CPU time & allocated memory on the sidebar. Only the embedded collector will show percentages for old data. Would you consider include this into glowroot?
![image](https://user-images.githubusercontent.com/6136404/83678845-0cdc1600-a5e7-11ea-91be-7ad2f6a3cc09.png)

2020-06-03 19:21 UTC, trask commented
Hey @ionutursuleanu, yes, this looks nice. Can I ask, what do you mean by

> Only the embedded collector will show percentages for old data.

2020-06-03 19:58 UTC, ionutursuleanu commented
> Hey @ionutursuleanu, yes, this looks nice. Can I ask, what do you mean by
> 
> > Only the embedded collector will show percentages for old data.

By old data I mean what you see in glowroot before a version update. 

For the embedded collector I just used existing values from aggregate_tn_rollup_:
- total_cpu_nanos = sum(main_thread_total_cpu_nanos) + sum(aux_thread_total_cpu_nanos)
- total_allocated_bytes = sum(main_thread_total_allocated_bytes) + sum(aux_thread_total_allocated_bytes)

With the central collector was a bit more complicated due to cassandra tables structure. I had to add 2 new columns(total_cpu_nanos & total_allocated_bytes) into aggregate_tt_summary_rollup_ & aggregate_tn_summary_rollup_ Existing rows in those tables will have null as default value. Only new rows will be inserted will actual cpu time / allocated bytes. This is were I'm not sure if I can populate those 2 columns will something calculated from other tables.

2020-06-03 20:02 UTC, trask commented
> By old data I mean what you see in glowroot before a version update.

Makes sense, that's fine.

2021-01-29 08:32 UTC, bmarwell requested changes
Whitespace nits

2021-01-29 08:32 UTC, bmarwell commented on agent/embedded/src/main/java/org/glowroot/agent/embedded/repo/AggregateDao.java
> +                throw new AssertionError("Unexpected sort order: " + sortOrder);
Is this whitespace change necessary?

2021-01-29 08:32 UTC, bmarwell commented on central/src/main/java/org/glowroot/central/repo/AggregateDaoImpl.java
> +        int i = startIndex;
Although sibling methods do not have this and it is a private method, a short Javadoc would be really nice:
When is an `IOException` thrown?
What are valid parameter ranges?
What does the method do (short summary)?

2021-01-29 08:32 UTC, bmarwell commented on common/src/main/java/org/glowroot/common/model/TransactionNameSummaryCollector.java
> +            throw new AssertionError("Unexpected sort order: " + sortOrder);
Same. Why change whitespace?

2021-01-29 08:32 UTC, bmarwell commented on ui/app/scripts/routes.js
> +            'total-time': 'By total time (%)',
Bravo 👏 for spotting this! :)

2021-08-07 20:52 UTC, gonchik commented
@trask  Do you have a plan to merge that PR ? 
What exactly need to be done to be merged?
I will be happy to start use as new release on my installations.

2021-11-20 22:37 UTC, trask approved these changes
@ionutursuleanu thx, everything looks great!

the only thing I'm still thinking about is that the dropdown options are a bit overwhelming, especially the difference between "total % and "average" is confusing for the different options (which was a problem before this PR too).

if I can't think of any better organization/display, will merge with current option list

2022-03-21 03:23 UTC, merged

2022-03-21 10:17 UTC, gonchik commented
@trask  Awesome! Thank you!

2022-04-13 15:47 UTC, lfen21 commented
it's work very well. Thanks